@base = http://localhost:3001/v1

GET http://localhost:3001/ping


### 

POST {{base}}/items
Content-Type: application/json

{
    "title":"Task 1",
    "description":"this is description task 1",
    "status":"Done"
}

### 

POST {{base}}/items
Content-Type: application/json

{
    "title":"Task 11",
    "description":"this is description task 11"
}

###
GET {{base}}/items/1

### 

PUT {{base}}/items/19
Content-Type: application/json

{
    "title":"Task 9 abs",
    "description":"this is description task 9 update",
    "status":"Done"
}

###
DELETE  {{base}}/items/10

###
GET   {{base}}/items?page=1&limit=10&status=Doing
